name: $(version)-$(Build.SourceBranchName).$(Build.BuildId)

pool:
  name: Home PC

resources:
  repositories:
  - repository: templates
    type: git
    name: templates

variables:
- name: version
  value: 0.4.0

jobs:
  - job: Build
    steps:
      - powershell: |
          if("$(Build.SourceBranchName)" -eq "master" -Or "$(Build.SourceBranchName)" -eq "main") { 
            Write-Host "##vso[task.setvariable variable=version]$(version)" 
            Write-Host "##vso[build.updatebuildnumber]$(version)"
          } else {
            Write-Host "##vso[task.setvariable variable=version]$(version)-$(Build.SourceBranchName).$(Build.BuildId)" 
            Write-Host "##vso[build.updatebuildnumber]$(version)-$(Build.SourceBranchName).$(Build.BuildId)"
          }
        displayName: Configure Version
      - powershell: |
          echo "$(System.AccessToken)" | az devops login --organization $(System.CollectionUri)
          $projectVariables = az pipelines variable-group list --organization $(System.CollectionUri)--project $(System.TeamProject)) --group HelmCharts | ConvertFrom-Json
          $options = "--target=Publish Helm Chart, --chart_version=$(Build.BuildNumber)" -split ","
          $projectVariables.variables.PSObject.Properties | where {$_.Value.value -ne $null} | forEach { $options+= "--$($_.Name)=$($_.Value.value)"  }
          .\build.ps1 @options
        displayName: 'Run Cake Script'        
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: './artifacts/helm/'
          ArtifactName: 'helm'
          publishLocation: 'Container'

