replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: [{ name: magnoxium-repository }]

nameOverride: ""
namespace: ""

hostname: ""

healthProbe: "/health"

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

autoscaling:
  enabled: false

appsettings:
  config: ""
  secrets: ""